// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


var someTodo = /* record */[
  /* description */"Some todo description",
  /* progress : DONE */1
];

var someTodoProgress = "Done";

var someTodos = /* :: */[
  someTodo,
  /* [] */0
];

console.log(someTodoProgress);

console.log(someTodo);

console.log(someTodos);

exports.someTodo = someTodo;
exports.someTodoProgress = someTodoProgress;
exports.someTodos = someTodos;
/*  Not a pure module */
