// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


var someTodo = /* record */[
  /* description */"Some todo description",
  /* progress : IN_PROGRESS */0
];

console.log(someTodo);

exports.someTodo = someTodo;
/*  Not a pure module */
